export { BrowserWindow } from './BrowserWindow';
export { TerminalWindow } from './TerminalWindow';
export { FilesWindow } from './FilesWindow';
export { EditorWindow } from './EditorWindow';
export { ChatWindow } from './ChatWindow';
export { SettingsWindow } from './SettingsWindow';
export { ComputerWindow } from './ComputerWindow';
export { AboutWindow } from './AboutWindow';
export { SetupWizard } from './SetupWizard';
