import { z } from 'zod';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

// Goal schema
const GoalSchema = z.object({
  id: z.string(),
  description: z.string(),
  priority: z.enum(['high', 'medium', 'low']).default('medium'),
  status: z.enum(['active', 'paused', 'completed']).default('active'),
  context: z.string().optional(),
});

// Schedule schema (cron-like)
const ScheduleSchema = z.object({
  id: z.string(),
  cron: z.string(), // Cron expression like "0 */2 * * *"
  action: z.string(),
  enabled: z.boolean().default(true),
});

// TinyFish config schema
const TinyFishSchema = z.object({
  apiKey: z.string().default(''),
  baseUrl: z.string().default('https://agent.tinyfish.ai'),
  defaultProfile: z.enum(['lite', 'stealth']).default('lite'),
});

// AgentMail config schema
const AgentMailSchema = z.object({
  apiKey: z.string().default(''),
  inboxUsername: z.string().default(''),
});

// Full config schema
const ConfigSchema = z.object({
  openrouter: z.object({
    apiKey: z.string(),
    model: z.string().default('nvidia/nemotron-3-nano-30b-a3b:free'),
    baseUrl: z.string().default('https://openrouter.ai/api/v1'),
  }),
  tinyfish: TinyFishSchema.default({
    apiKey: '',
    baseUrl: 'https://agent.tinyfish.ai',
    defaultProfile: 'lite',
  }),
  agentmail: AgentMailSchema.default({
    apiKey: '',
    inboxUsername: '',
  }),
  identity: z.object({
    name: z.string().default('BoneClaw Agent'),
    description: z.string().default('An autonomous AI agent'),
  }),
  goals: z.array(GoalSchema).default([]),
  schedules: z.array(ScheduleSchema).default([]),
  memory: z.object({
    persistPath: z.string().default('./.boneclaw/memory'),
    maxContextTokens: z.number().default(8000),
  }),
  heartbeat: z.object({
    intervalMs: z.number().default(60000),
  }),
  workspace: z.string().default(process.cwd()),
});

export type Config = z.infer<typeof ConfigSchema>;
export type Goal = z.infer<typeof GoalSchema>;
export type Schedule = z.infer<typeof ScheduleSchema>;

// Default config
const DEFAULT_CONFIG: Config = {
  openrouter: {
    apiKey: '',
    model: 'nvidia/nemotron-3-nano-30b-a3b:free',
    baseUrl: 'https://openrouter.ai/api/v1',
  },
  tinyfish: {
    apiKey: '',
    baseUrl: 'https://agent.tinyfish.ai',
    defaultProfile: 'lite',
  },
  agentmail: {
    apiKey: '',
    inboxUsername: '',
  },
  identity: {
    name: 'BoneClaw Agent',
    description: 'An autonomous AI agent',
  },
  goals: [],
  schedules: [],
  memory: {
    persistPath: './.boneclaw/memory',
    maxContextTokens: 8000,
  },
  heartbeat: {
    intervalMs: 60000,
  },
  workspace: process.cwd(),
};

/**
 * Parse the YAML config format used by the backend.
 * This is a lightweight parser that handles the specific YAML structure
 * generated by the backend's generateBoneclawConfig() function.
 * 
 * Maps the YAML format to boneclaw's internal Config type:
 *   YAML llm.openrouter.api_key -> Config openrouter.apiKey
 *   YAML llm.default_model      -> Config openrouter.model
 *   YAML agent.max_context_tokens -> Config memory.maxContextTokens
 *   YAML tools.exec.workspace   -> Config workspace
 */
function parseYamlConfig(content: string): Partial<Config> {
  const config: Partial<Config> = {};
  
  // Extract OpenRouter API key: openrouter:\n    api_key: "..."
  const apiKeyMatch = content.match(/openrouter:\s*\n\s*api_key:\s*"([^"]*)"/m);
  const apiKey = apiKeyMatch ? apiKeyMatch[1] : '';
  
  // Extract model: default_model: "..."
  const modelMatch = content.match(/default_model:\s*"([^"]*)"/m);
  const model = modelMatch ? modelMatch[1] : '';
  
  // Extract max context tokens: max_context_tokens: N
  const contextMatch = content.match(/max_context_tokens:\s*(\d+)/m);
  const maxContextTokens = contextMatch ? parseInt(contextMatch[1], 10) : undefined;
  
  // Extract workspace: workspace: /path
  const workspaceMatch = content.match(/exec:\s*\n\s*workspace:\s*(\S+)/m);
  const workspace = workspaceMatch ? workspaceMatch[1] : undefined;
  
  // Extract TinyFish API key: tinyfish:\n    api_key: "..."
  const tinyfishKeyMatch = content.match(/tinyfish:\s*\n\s*api_key:\s*"([^"]*)"/m);
  const tinyfishApiKey = tinyfishKeyMatch ? tinyfishKeyMatch[1] : '';
  
  // Extract AgentMail config: agentmail:\n    api_key: "..."\n    inbox_username: "..."
  const agentmailKeyMatch = content.match(/agentmail:\s*\n\s*api_key:\s*"([^"]*)"/m);
  const agentmailApiKey = agentmailKeyMatch ? agentmailKeyMatch[1] : '';
  const agentmailUsernameMatch = content.match(/agentmail:\s*[\s\S]*?inbox_username:\s*"([^"]*)"/m);
  const agentmailInboxUsername = agentmailUsernameMatch ? agentmailUsernameMatch[1] : '';
  
  // Extract transport port: port: N
  const portMatch = content.match(/transport:\s*\n\s*http:\s*\n\s*enabled:\s*true\s*\n\s*port:\s*(\d+)/m);
  const _port = portMatch ? parseInt(portMatch[1], 10) : undefined;
  
  if (apiKey || model) {
    config.openrouter = {
      ...DEFAULT_CONFIG.openrouter,
      ...(apiKey ? { apiKey } : {}),
      ...(model ? { model } : {}),
    };
  }
  
  if (tinyfishApiKey) {
    config.tinyfish = {
      ...DEFAULT_CONFIG.tinyfish,
      apiKey: tinyfishApiKey,
    };
  }
  
  if (agentmailApiKey || agentmailInboxUsername) {
    config.agentmail = {
      ...DEFAULT_CONFIG.agentmail,
      ...(agentmailApiKey ? { apiKey: agentmailApiKey } : {}),
      ...(agentmailInboxUsername ? { inboxUsername: agentmailInboxUsername } : {}),
    };
  }
  
  if (maxContextTokens) {
    config.memory = {
      ...DEFAULT_CONFIG.memory,
      maxContextTokens,
    };
  }
  
  if (workspace) {
    config.workspace = workspace;
  }
  
  return config;
}

/**
 * Load config from file or environment.
 * Supports both JSON and YAML config files.
 */
export function loadConfig(configPath?: string): Config {
  let config: Partial<Config> = {};
  
  // Try to load from file
  const paths = [
    configPath,
    process.env.BONECLAW_CONFIG,
    join(process.cwd(), '.boneclaw', 'config.json'),
    join(process.env.HOME || '', '.boneclaw', 'config.json'),
  ].filter(Boolean) as string[];
  
  for (const p of paths) {
    if (existsSync(p)) {
      try {
        const content = readFileSync(p, 'utf-8');
        
        // Detect format: try JSON first, then YAML
        if (content.trimStart().startsWith('{')) {
          config = JSON.parse(content);
        } else {
          // YAML format (from backend)
          config = parseYamlConfig(content);
        }
        break;
      } catch {
        // Continue to next path
      }
    }
  }
  
  // Override with environment variables
  if (process.env.OPENROUTER_API_KEY) {
    config.openrouter = {
      ...DEFAULT_CONFIG.openrouter,
      ...config.openrouter,
      apiKey: process.env.OPENROUTER_API_KEY,
    };
  }
  
  if (process.env.OPENROUTER_MODEL) {
    config.openrouter = {
      ...DEFAULT_CONFIG.openrouter,
      ...config.openrouter,
      model: process.env.OPENROUTER_MODEL,
    };
  }
  
  if (process.env.BONECLAW_WORKSPACE) {
    config.workspace = process.env.BONECLAW_WORKSPACE;
  }
  
  // Override with TinyFish env var
  if (process.env.TINYFISH_API_KEY) {
    config.tinyfish = {
      ...DEFAULT_CONFIG.tinyfish,
      ...config.tinyfish,
      apiKey: process.env.TINYFISH_API_KEY,
    };
  }
  
  // Override with AgentMail env vars
  if (process.env.AGENTMAIL_API_KEY) {
    config.agentmail = {
      ...DEFAULT_CONFIG.agentmail,
      ...config.agentmail,
      apiKey: process.env.AGENTMAIL_API_KEY,
    };
  }
  
  // Merge with defaults and validate
  const merged = {
    ...DEFAULT_CONFIG,
    ...config,
    openrouter: { ...DEFAULT_CONFIG.openrouter, ...config.openrouter },
    tinyfish: { ...DEFAULT_CONFIG.tinyfish, ...config.tinyfish },
    agentmail: { ...DEFAULT_CONFIG.agentmail, ...config.agentmail },
    identity: { ...DEFAULT_CONFIG.identity, ...config.identity },
    memory: { ...DEFAULT_CONFIG.memory, ...config.memory },
    heartbeat: { ...DEFAULT_CONFIG.heartbeat, ...config.heartbeat },
  };
  
  return ConfigSchema.parse(merged);
}

/**
 * Get a config value for display (masks sensitive values)
 */
export function getConfigSummary(config: Config): Record<string, unknown> {
  return {
    model: config.openrouter.model,
    name: config.identity.name,
    goals: config.goals.length,
    schedules: config.schedules.length,
    workspace: config.workspace,
    hasApiKey: !!config.openrouter.apiKey,
    hasTinyfishKey: !!config.tinyfish.apiKey,
    hasAgentmailKey: !!config.agentmail.apiKey,
  };
}
